TAG-138: Sett opp Grafana dashboard for tekniske metrikker
navikt/tag-kontaktskjema pull request #7
Opened 2018-12-11 14:03 UTC by andrmos

Kan sees [her](https://grafana.adeo.no/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-sbs&var-app=tag-kontaktskjema&var-namespace=All&var-docker_image=79&var-ingress_url=All).
Ble mye testing fram og tilbake, og fikk ikke til metrikkene for JVM. Har laget en ny [Jira sak](https://jira.adeo.no/browse/TAG-140) på dette.

2018-12-11 14:05 UTC, andrmos commented on prod-nais.yaml
> +    - https://tag-kontaktskjema.nais.oera.no
Er dette riktig ingress for prod?

2018-12-12 10:11 UTC, Lars-Andreas requested changes
CORS-kall fra veiviseren feiler i testmiljø

2018-12-12 10:11 UTC, LarsAndreasNav commented on prod-nais.yaml
> +    - https://tag-kontaktskjema.nais.oera.no
Det ser riktig ut!

2018-12-17 12:31 UTC, Lars-Andreas approved these changes
CORS-feilen var grunnet toggling av endepunktet, hadde ingenting med de øvrige endringene å gjøre

2018-12-17 12:34 UTC, merged